'use strict';

const test = require('..');
const exec = require('./exec');


test('harness before and after', async function () {
  let result;

  result = await exec('test/spawn/before-after.js');
  this.eq(result.stdout, [
    '',
    '  1 Test 1 _ ms',
    '',
    '    Top-level before',
    '',
    '      1.1 Subtest 1 (inline) _ ms',
    '',
    '        Before 1',
    '        After 1',
    '',
    '      1.2 Subtest 4 (inline) _ ms',
    '',
    '        Before 1',
    '        Before 2',
    '        After 1',
    '        After 2',
    '',
    '    ✔ ok',
    '',
    '      1.3 Subtest 2 (harness) _ ms',
    '',
    '        Before 1',
    '        Before 2',
    '        After 1',
    '        After 2',
    '',
    '      1.4 Subtest 3 (harness) _ ms',
    '',
    '        Before 1',
    '        Before 2',
    '        After 1',
    '        After 2',
    '',
    '    Top-level after',
    '',
    '  2 Test 2 _ ms',
    '',
    '    Top-level before',
    '',
    '      2.1 none _ ms',
    '',
    '        Before all',
    '        Not before A',
    '        Not before B',
    '        Not before A or B',
    '        After all',
    '        Not after A',
    '        Not after B',
    '        Not after A or B',
    '',
    '      2.2 A _ ms',
    '',
    '        Before all',
    '        Before A',
    '        Before A or B',
    '        Not before B',
    '        After all',
    '        After A',
    '        After A or B',
    '        Not after B',
    '',
    '      2.3 B _ ms',
    '',
    '        Before all',
    '        Before B',
    '        Before A or B',
    '        Not before A',
    '        After all',
    '        After B',
    '        After A or B',
    '        Not after A',
    '',
    '      2.4 A and B _ ms',
    '',
    '        Before all',
    '        Before A',
    '        Before B',
    '        Before A or B',
    '        After all',
    '        After A',
    '        After B',
    '        After A or B',
    '',
    '    Top-level after',
    '',
    '',
    '  All tests passed!',
    '',
    '',
    '  Total:      10 tests   1 assertion',
    '  Passing:    10 tests   1 assertion',
    '  Duration:   _ ms',
    ''], 'before and after');

  result = await exec('test/spawn/before.js');
  this.eq(result.stdout.filter(x => !/^\s+ at /.test(x)), [
    '',
    '  1 test 1 _ ms',
    '',
    '    ✔ before',
    '',
    '    ✘ before',
    '',
    '      At:       ./test/spawn/before.js (10:8)',
    '      Operator: fail',
    '',
    '    ✘ uncaught error',
    '',
    '      At:       ./test/spawn/before.js (13:6)',
    '      Operator: error',
    '      Actual:',
    '        Error: fail',
    '',
    '  2 test 2 _ ms',
    '',
    '    ✔ before',
    '',
    '    ✘ before',
    '',
    '      At:       ./test/spawn/before.js (10:8)',
    '      Operator: fail',
    '',
    '    ✘ uncaught error',
    '',
    '      At:       ./test/spawn/before.js (13:6)',
    '      Operator: error',
    '      Actual:',
    '        Error: fail',
    '',
    '',
    '  Failed Tests: There was 2 failed tests with 4 failed assertions!',
    '',
    '',
    '  Total:      2 tests   6 assertions',
    '  Passing:    0 tests   2 assertions',
    '  Failing:    2 tests   4 assertions',
    '  Duration:   _ ms',


    ''], 'before');

  result = await exec('test/spawn/after.js');
  this.eq(result.stdout.filter(x => !/^\s+ at /.test(x)), [
    '',
    '  1 test 1 _ ms',
    '',
    '    ✔ test 1',
    '    ✔ after',
    '',
    '    ✘ after',
    '',
    '      At:       ./test/spawn/after.js (10:8)',
    '      Operator: fail',
    '',
    '    ✘ uncaught error',
    '',
    '      At:       ./test/spawn/after.js (13:6)',
    '      Operator: error',
    '      Actual:',
    '        Error: fail',
    '',
    '  2 test 2 _ ms',
    '',
    '    ✔ test 2',
    '    ✔ after',
    '',
    '    ✘ after',
    '',
    '      At:       ./test/spawn/after.js (10:8)',
    '      Operator: fail',
    '',
    '    ✘ uncaught error',
    '',
    '      At:       ./test/spawn/after.js (13:6)',
    '      Operator: error',
    '      Actual:',
    '        Error: fail',
    '',
    '',
    '  Failed Tests: There was 2 failed tests with 4 failed assertions!',
    '',
    '',
    '  Total:      2 tests   8 assertions',
    '  Passing:    0 tests   4 assertions',
    '  Failing:    2 tests   4 assertions',
    '  Duration:   _ ms',
    ''], 'after');
});
